### ISSUE TITLE
Relationship type cannot be customized

### ISSUE THREAD

**Issue by chrism** [empress/broccoli-static-site-json#16]
A simple relationship like this works fine by adding the relationship to the model

```js
import DS from 'ember-data';

export default DS.Model.extend({
  images: DS.hasMany('image')
});
```

Including it as a reference in the StaticSiteJson

```js
new StaticSiteJson('example', {
  ...
  references: [
    'images'
  ]
});
```

And in the markdown

```md
---
id: example
images: ['image-1', 'image-2']
---
```

But what about if the relationship name is different to the type?

For example

```js
import DS from 'ember-data';

export default DS.Model.extend({
  images: DS.hasMany('image'),
  coverImage: DS.belongsTo('image')
});
```

```js
new StaticSiteJson('example', {
  ...
  references: [
    'images',
    'coverImage'
  ]
});
```

```md
---
id: example
coverImage: big-image
images: ['image-1', 'image-2']
---
```

The resulting JSON is then in the form within the relationship key like this

```json
{
  "coverImage": {
    "data": {
      "type": "coverImages",
      "id": "big-image"
    }
  }
}
```

But, the type should be "images" here, so there is an error and there doesn't seem to be an obvious way to override this currently.

Do you think there should be a way to customize the realtionship type directly from the frontmatter without the need to adapt the serializers to account for this incorrect type?

I'm not sure how common this use case is although I feel like it's fairly standard.

**Comment by billybonks** [comment]
I am thinking that a Type resolution hash would be the best approach here. since the frontmatter is written multiple times doesn't make sense to manage its type in the YML itself but rather the compiler

```
new StaticSiteJson('example', {
  ...
  references: [
    'images',
    'coverImage'
  ],
  refrenceTypeResolutions: {
   coverImage: 'image'
 }
});
```

**Comment by chrism** [comment]
I agree, tbh in the end it was a showstopper for me so went with another solution.

I’d still really like to try use this on a project one day to take advantage of Fastboot with Prender so would be really happy to see any kind of solution.
